# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
# Built with Arduino IDE 2:1.0.5 and Arduino-Makefile
# Added Pro Trinket to Ardunio IDE boards.txt using: /home/reedb/projects/arduino/pro_trinket_boards.txt
# Use UNO as board tag since the Pro Trinket is 5V/16MHz, w/ LED on D13 (PB5)
#

BOARD_TAG = uno
include /usr/share/arduino/Arduino.mk
